import org.telegram.telegrambots.meta.exceptions.TelegramApiException;

import java.io.IOException;

public class Main {
    public static void main(String[] args) throws TelegramApiException {

        new NasaBot("Nasa_34",
                "5535913521:AAEif1fbOekC2lCY7kdzkaNf_c_ZZhLY_cM");
    }
}